# Generated by Django 6.1 on 2026-08-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
